### ISSUE TITLE
Any thoughts about extending this to cover more APIs?

### ISSUE THREAD

**Issue by kevincantu** [opteemister/terraform-provider-sendgrid#3]
Particularly, I'm curious about what it would take to extend your stuff here to cover adding more IPs to their whitelist:
https://sendgrid.com/docs/API_Reference/api_v3.html

**Comment by kevincantu** [comment]
Maybe I'm missing something, but I don't see a GitHub repo for the library used here?
https://github.com/opteemister/terraform-provider-sendgrid/blob/master/sendgrid/config.go#L6

**Comment by opteemister** [comment]
Hi, it was developed several years ago. And not maintained anymore (( 
But I saw that there are several forks which could have more API supports.https://github.com/opteemister/terraform-provider-sendgrid/network/members

**Comment by kevincantu** [comment]
Ahh, thanks!
